runtime:
  seed: &seed 131
  deepspeed: True
  gradient_checkpointing: True
  gradient_accumulation_steps: &gas 8
  bf16: &bf16 True
  fp16: &fp16 False

deepspeed:
  enabled: True
  config:
    zero_optimization:
      stage: 2
      allgather_partitions: true
      allgather_bucket_size: 1.0e+8
      overlap_comm: true
      reduce_scatter: true
      reduce_bucket_size: 1.0e+8
      contiguous_gradients: true
    bf16:
      enabled: *bf16
    fp16:
      enabled: *fp16
      loss_scale: 0
      loss_scale_window: 100
      initial_scale_power: 16
      hysteresis: 2
      min_loss_scale: 1.0e-10
    steps_per_print: 2000
    gradient_clipping: 1.0
    wall_clock_breakdown: False
    zero_allow_untested_optimizer: true
    train_micro_batch_size_per_gpu: "auto"
    train_batch_size: "auto"
    gradient_accumulation_steps: *gas

tokenizer:
  type: BaiChuan2Tokenizer
  kwargs:
    tokenizer_name_or_path: &file_path baichuan2_7b_base
    bos_token: "<s>"
    eos_token: "</s>"
    unk_token: "<unk>"
    use_auth_token: False


tokenization: &tokenization
  type: sense_tokenization
  kwargs:
    with_tokenizer: True
    max_seq_length: &train_seq_length 2048
    parser_type: simple_chat

infer_cfg:
  eval_task: ceval  # base, ceval, cmmlu, human_eval
  question_file: questions.jsonl
  result_file: results.jsonl
  generation_cfg:
    temperature: 0.2
    top_k: 40
    top_p: 0.9
    do_sample: True
    num_beams: 1
    repetition_penalty: 1.3
    max_new_tokens: 512

infer_tokenization: 
  type: sense_tokenization
  kwargs:
    max_seq_length: *train_seq_length 
    parser_type: base
    parser_kwargs:
      prompt_type: baichuan2

data:
  data_types: [train]
  train:
    dataset:
      type: base_nlp_json
      kwargs:
        json_file: sft_data.jsonl
        transformer: [*tokenization]
        json_type: line
    batch_collector:
      type: batch_align
      kwargs:
        alignment: 1
        max_seq_length: *train_seq_length
    batch_sampler:
      type: base
      kwargs:
        sampler:
          type: dist
        batch_size: 8
    data_loader:
      type: base
      kwargs:
        num_workers: 4
        pin_memory: True
        seed: *seed

trainer:
  train_iters: &train_iters 1000
  optimizer:
    type: AdamW
    kwargs:
      lr: 2.e-5
      weight_decay: 0
      betas: [0.9, 0.95]
      eps: 1.e-8
  lr_scheduler:
    type: hf_cosine
    kwargs:
      warmup_steps: 30
      training_steps: *train_iters

saver:
  enabled: True
  save_interval: 200
  save_path: checkpoints/baichuan2_7b
  save_mode: deepspeed
  save_optim: True
  save_rng_state: True


loader:
  enabled: True
  load_path: checkpoint-1000
  load_mode: huggingface
  load_optim: True
  load_rng_state: True


hooks:
  - type: hf_train_val_logger
    kwargs:
      log_interval: 10
      tensorboard: False
  - type: dynamic_checkpoint
    kwargs:
        enable: False
        debug_freq: 10
        strategy:
          type: predefine
          kwargs:
            size_map:
              512: 0 
              1024: 16
              2048: 16

model:
  type: BaiChuan2ForCausalLM
  kwargs:
    model_name_or_path: *file_path
    torch_dtype: bfloat16
    trust_remote_code: True
